# Generated by Django 3.0.3 on 2020-12-03 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=100)),
                ('catdes', models.CharField(max_length=300)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('complainttype', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('complaintdetail', models.CharField(max_length=300, null=True)),
                ('complaintfile', models.FileField(null=True, upload_to='')),
                ('regdate', models.DateField()),
                ('status', models.CharField(max_length=50, null=True)),
                ('lastupdationdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=100)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
                ('userimage', models.FileField(null=True, upload_to='')),
                ('regdate', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=100)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('categoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaint.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('remarkdate', models.DateField(null=True)),
                ('complaintid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaint.Complaint')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaint.tblUser'),
        ),
    ]
