# Generated by Django 3.0.3 on 2021-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='noc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
