# Generated by Django 3.0.3 on 2021-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_noc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaintfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
