# Generated by Django 3.0.3 on 2021-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_auto_20210527_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='remarkdate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='ComplaintRemark',
        ),
    ]
